In [2]:
import pandas as pd

listings_raw = pd.read_csv("../data_raw/listings.csv")
calendar_raw = pd.read_csv("../data_raw/calendar.csv")
reviews_raw = pd.read_csv("../data_raw/reviews.csv")

print("LISTINGS:")
display(listings_raw.head())

print("CALENDAR:")
display(calendar_raw.head())

print("REVIEWS:")
display(reviews_raw.head())

C:\Users\cebal\AppData\Local\Temp\ipykernel_37520\2403036867.py:3: DtypeWarning: Columns (61,62,95) have mixed types. Specify dtype option on import or set low_memory=False.
  listings_raw = pd.read_csv("../data_raw/listings.csv")

LISTINGS:

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,11508,https://www.airbnb.com/rooms/11508,20200426042522,2020-04-26,Amazing Luxurious Apt-Palermo Soho,NaN,LUXURIOUS NEW APT: 1 BDRM- POOL/ GYM/ SPA/ 24-...,LUXURIOUS NEW APT: 1 BDRM- POOL/ GYM/ SPA/ 24-...,none,AREA: PALERMO SOHO Minutes walking distance fr...,...,f,f,strict_14_with_grace_period,f,f,1,1,0,0,0.27
1,12463,https://www.airbnb.com/rooms/12463,20200426042522,2020-04-26,Room in Recoleta - awesome location,My apartment is centrally located in Recoleta ...,This is a very comfortable pull-out sofa in th...,My apartment is centrally located in Recoleta ...,none,It's near the school of medicine so the street...,...,f,f,moderate,f,f,1,0,1,0,0.16
2,13095,https://www.airbnb.com/rooms/13095,20200426042522,2020-04-26,Standard Room at Palermo Viejo B&B,Palermo Viejo B&B is a typical home in one of ...,Standard room : Palermo Viejo Bed & Breakfast ...,Palermo Viejo B&B is a typical home in one of ...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,7,0,7,0,0.06
3,13096,https://www.airbnb.com/rooms/13096,20200426042522,2020-04-26,Standard Room in Palermo Viejo B&B,Palermo Viejo B&B is a typical home in one of ...,Palermo Viejo Bed & Breakfast is located in a ...,Palermo Viejo B&B is a typical home in one of ...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,7,0,7,0,NaN
4,13097,https://www.airbnb.com/rooms/13097,20200426042522,2020-04-26,Standard Room at Palermo Viejo B&B,Palermo Viejo B&B is a typical home in one of ...,Palermo Viejo Bed & Breakfast is located in a ...,Palermo Viejo B&B is a typical home in one of ...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,7,0,7,0,1.89

CALENDAR:

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,50778,2020-04-26,f,"$2,655.00","$2,655.00",5.0,1125.0
1,133654,2020-04-27,t,"$1,150.00","$1,150.00",4.0,1125.0
2,133654,2020-04-28,t,"$1,150.00","$1,150.00",4.0,1125.0
3,133654,2020-04-29,t,"$1,150.00","$1,150.00",4.0,1125.0
4,133654,2020-04-30,t,"$1,150.00","$1,150.00",4.0,1125.0

REVIEWS:

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,11508,1615861,2012-07-02,877808,Charlie,Amazing place!\r\n\r\nLocation: short walk to ...
1,11508,3157005,2012-12-26,656077,Shaily,Really enjoyed Candela's recommendations and q...
2,11508,3281011,2013-01-05,2835998,Michiel,Candela and her colleague were very attentive ...
3,11508,6050019,2013-07-28,4600436,Tara,"The apartment was in a beautiful, modern build..."
4,11508,9328455,2013-12-22,3130017,Simon,My stay at Candela's apartment was very enjoya...

In [3]:
cols_listings = [
    "id",
    "name",
    "host_id",
    "host_name",
    "neighbourhood",
    "latitude",
    "longitude",
    "room_type",
    "price",
    "minimum_nights",
    "number_of_reviews",
    "last_review",
    "reviews_per_month",
    "calculated_host_listings_count",
    "availability_365",
]

listings = listings_raw[cols_listings].copy()

listings.head()

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,11508,Amazing Luxurious Apt-Palermo Soho,42762,Candela,Palermo,-34.58184,-58.42415,Entire home/apt,"$3,983.00",2,26,2019-11-28,0.27,1,365
1,12463,Room in Recoleta - awesome location,48799,Matt,Recoleta,-34.59761,-58.39468,Private room,"$1,593.00",1,20,2017-12-11,0.16,1,365
2,13095,Standard Room at Palermo Viejo B&B,50994,Ariel,Palermo,-34.59382,-58.42994,Private room,"$2,987.00",1,1,2018-12-18,0.06,7,365
3,13096,Standard Room in Palermo Viejo B&B,50994,Ariel,Palermo,-34.59398,-58.42853,Private room,"$2,987.00",1,0,NaN,NaN,7,365
4,13097,Standard Room at Palermo Viejo B&B,50994,Ariel,Palermo,-34.59348,-58.42949,Private room,"$2,987.00",1,66,2019-11-27,1.89,7,365

In [4]:
listings["price_numeric"] = (
    listings["price"]
    .astype(str)                     
    .str.replace("$", "", regex=False)   
    .str.replace(",", "", regex=False)  
    .str.strip()                          
    .astype(float)                        
)

listings[["price", "price_numeric"]].head()

       price  price_numeric
0  $3,983.00         3983.0
1  $1,593.00         1593.0
2  $2,987.00         2987.0
3  $2,987.00         2987.0
4  $2,987.00         2987.0

In [5]:
listings["last_review"] = pd.to_datetime(listings["last_review"], errors="coerce")

listings["reviews_per_month"] = listings["reviews_per_month"].fillna(0)

listings = listings.dropna(subset=["price_numeric", "latitude", "longitude"])

listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23729 entries, 0 to 23728
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              23729 non-null  int64
 1   name                            23719 non-null  object
 2   host_id                         23729 non-null  int64
 3   host_name                       23726 non-null  object
 4   neighbourhood                   23729 non-null  object
 5   latitude                        23729 non-null  float64
 6   longitude                       23729 non-null  float64
 7   room_type                       23729 non-null  object
 8   price                           23729 non-null  object
 9   minimum_nights                  23729 non-null  int64
 10  number_of_reviews               23729 non-null  int64
 11  last_review                     17222 non-null  datetime64[ns]
 12  reviews_per_month               23729 non-null  float64
 13  calculated_host_listings_count  23729 non-null  int64
 14  availability_365                23729 non-null  int64
 15  price_numeric                   23729 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(6), object(5)
memory usage: 2.9+ MB

In [6]:
listings["price_30_days"] = listings["price_numeric"] * 30

In [7]:
q1 = listings["price_numeric"].quantile(0.33)
q2 = listings["price_numeric"].quantile(0.66)

def price_category(p):
    if p <= q1:
        return "low"
    elif p <= q2:
        return "medium"
    return "high"

listings["price_category"] = listings["price_numeric"].apply(price_category)

listings[["price_numeric", "price_category"]].head()

   price_numeric price_category
0         3983.0           high
1         1593.0            low
2         2987.0           high
3         2987.0           high
4         2987.0           high

In [8]:
listings.to_csv("../data_clean/listings_clean.csv", index=False, encoding="utf-8")

In [9]:
pd.read_csv("../data_clean/listings_clean.csv").head()

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,price_numeric,price_30_days,price_category
0,11508,Amazing Luxurious Apt-Palermo Soho,42762,Candela,Palermo,-34.58184,-58.42415,Entire home/apt,"$3,983.00",2,26,2019-11-28,0.27,1,365,3983.0,119490.0,high
1,12463,Room in Recoleta - awesome location,48799,Matt,Recoleta,-34.59761,-58.39468,Private room,"$1,593.00",1,20,2017-12-11,0.16,1,365,1593.0,47790.0,low
2,13095,Standard Room at Palermo Viejo B&B,50994,Ariel,Palermo,-34.59382,-58.42994,Private room,"$2,987.00",1,1,2018-12-18,0.06,7,365,2987.0,89610.0,high
3,13096,Standard Room in Palermo Viejo B&B,50994,Ariel,Palermo,-34.59398,-58.42853,Private room,"$2,987.00",1,0,NaN,0.00,7,365,2987.0,89610.0,high
4,13097,Standard Room at Palermo Viejo B&B,50994,Ariel,Palermo,-34.59348,-58.42949,Private room,"$2,987.00",1,66,2019-11-27,1.89,7,365,2987.0,89610.0,high

In [10]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23729 entries, 0 to 23728
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              23729 non-null  int64
 1   name                            23719 non-null  object
 2   host_id                         23729 non-null  int64
 3   host_name                       23726 non-null  object
 4   neighbourhood                   23729 non-null  object
 5   latitude                        23729 non-null  float64
 6   longitude                       23729 non-null  float64
 7   room_type                       23729 non-null  object
 8   price                           23729 non-null  object
 9   minimum_nights                  23729 non-null  int64
 10  number_of_reviews               23729 non-null  int64
 11  last_review                     17222 non-null  datetime64[ns]
 12  reviews_per_month               23729 non-null  float64
 13  calculated_host_listings_count  23729 non-null  int64
 14  availability_365                23729 non-null  int64
 15  price_numeric                   23729 non-null  float64
 16  price_30_days                   23729 non-null  float64
 17  price_category                  23729 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(6), object(6)
memory usage: 3.3+ MB

In [11]:
calendar = calendar_raw[
    ["listing_id", "date", "available", "price", "adjusted_price", "minimum_nights", "maximum_nights"]
].copy()

In [12]:
calendar["date"] = pd.to_datetime(calendar["date"], errors="coerce")

In [13]:
calendar["available"] = calendar["available"].map({"t": 1, "f": 0})

In [14]:
for col in ["price", "adjusted_price"]:
    calendar[col] = (
        calendar[col].astype(str)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    calendar[col] = pd.to_numeric(calendar[col], errors="coerce")

In [15]:
calendar.to_csv("../data_clean/calendar_clean.csv", index=False, encoding="utf-8")

In [16]:
calendar.head()
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8661286 entries, 0 to 8661285
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            datetime64[ns]
 2   available       int64
 3   price           float64
 4   adjusted_price  float64
 5   minimum_nights  float64
 6   maximum_nights  float64
dtypes: datetime64[ns](1), float64(4), int64(2)
memory usage: 462.6 MB

In [17]:
reviews = reviews_raw[
    ["listing_id", "id", "date", "reviewer_id", "reviewer_name", "comments"]
].copy()

reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,11508,1615861,2012-07-02,877808,Charlie,Amazing place!\r\n\r\nLocation: short walk to ...
1,11508,3157005,2012-12-26,656077,Shaily,Really enjoyed Candela's recommendations and q...
2,11508,3281011,2013-01-05,2835998,Michiel,Candela and her colleague were very attentive ...
3,11508,6050019,2013-07-28,4600436,Tara,"The apartment was in a beautiful, modern build..."
4,11508,9328455,2013-12-22,3130017,Simon,My stay at Candela's apartment was very enjoya...

In [18]:
reviews["date"] = pd.to_datetime(reviews["date"], errors="coerce")

In [19]:
reviews["year"] = reviews["date"].dt.year

In [20]:
reviews = reviews.dropna(subset=["date"])

In [21]:
reviews.to_csv("../data_clean/reviews_clean.csv", index=False, encoding="utf-8")

In [22]:
reviews.head()
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387099 entries, 0 to 387098
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     387099 non-null  int64
 1   id             387099 non-null  int64
 2   date           387099 non-null  datetime64[ns]
 3   reviewer_id    387099 non-null  int64
 4   reviewer_name  387099 non-null  object
 5   comments       386923 non-null  object
 6   year           387099 non-null  int32
dtypes: datetime64[ns](1), int32(1), int64(3), object(2)
memory usage: 19.2+ MB

In [23]:
pip install pyodbc sqlalchemy pandas

Requirement already satisfied: pyodbc in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (2.0.44)
Requirement already satisfied: pandas in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: greenlet>=1 in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\cebal\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
DRIVER_NAME = "MySQL ODBC 9.5 Unicode Driver"